trigger:
  batch: true
  branches:
    include:
    - main
    - dev
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: devops
      type: git
      name: devops
      ref: refs/heads/dev

variables:
  - template: pipelines/global-vars.yml@devops

pool:
  vmImage: $(vmImageName)

extends:
  template: pipelines/build-deploy-conapp.yml@devops
  parameters:
    appName: demo-python
    tag: dev
    registryServiceConnection: ${{ variables.registryServiceConnection }}
    armServiceConnection: ${{ variables.armServiceConnection }}
    dockerRegistryName: ${{ variables.dockerRegistryName }}
    subscriptionId: ${{ variables.subscriptionId }}
    location: ${{ variables.location }}
    resourceGroup: ${{ variables.resourceGroup }}
    identityName: ${{ variables.identityName }}
    containerAppEnvironment: ${{ variables.containerAppEnvironment }}
