trigger:
  batch: true
  branches:
    include:
    - main
    - dev
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: devops
      type: git
      name: devops
      ref: refs/heads/dev

extends:
  template: pipelines/build-deploy-conapp.yml@devops
  parameters:
    appName: demo-python
    tag: dev
