trigger:
  batch: true
  branches:
    include:
    - main
    - dev
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: devops
      type: git
      name: devops
      ref: refs/heads/dev

variables:
  vmImageName: ubuntu-latest
  location: westeurope
  dockerRegistryName: akazureregistry.azurecr.io
  registryServiceConnection: akazureregistry
  imageNamespace: learn
  appName: demoapp
  tag: dev
  armServiceConnection: AzureServiceConnection
  subscriptionId: b0570a95-0377-4937-8e15-6555b6f600f4
  identityName: DemoContainerApp
  resourceGroup: AzureLearn
  deployParamsFileName: deploy.parameters.json
  tfstateStorageAccount: aktfstate
  tfstateStorageContainer: tfstate
  skipBuild: false

pool:
  vmImage: $(vmImageName)

stages:
  # Build stage
  - stage: Build
    displayName: Build and push stage

    jobs:
    - job: Build
      displayName: Build Image
      condition: eq('${{ variables.skipBuild }}', false)

      steps:
    # Build docker image step
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: '${{ variables.imageNamespace }}/${{ variables.appName }}'
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        # Service connection name (ACR connection)
          containerRegistry: ${{ variables.registryServiceConnection }}
          tags: ${{ variables.tag }}
