[tool.ruff]
line-length = 120
target-version = "py311"

[tool.mypy]
plugins = [ "pydantic.mypy" ]
python_version = "3.11"
follow_imports = "silent"
show_column_numbers = true
pretty = false
implicit_optional = true
strict_optional = false
check_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = false

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_level = "DEBUG"
testpaths = [ "tests" ]
